version: '3.4'

services:
  sampleauthentication.net:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  database:
    container_name: database
    ports:
       - "1234:1433"
    environment:
       SA_PASSWORD: "Admin@123"
       ACCEPT_EULA: "Y"
    volumes:
     - databasedata:/var/opt/mssql

volumes:
  databasedata: